import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Amir Sorayaei Portfolio",
  description:
    "This is a Next.js app Generated by Amir Sorayaei as a Front-End developer portfolio",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <title>Amir Sorayaei</title>
      <head>
        {/* Google tag (gtag.js) */}
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-PTDXQBB1BC"
        />
      </head>
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
