import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Amir Sorayaei Portfolio",
  description:
    "This is a Next.js app Generated by Amir Sorayaei as a Front-End developer portfolio",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <title>Amir Sorayaei</title>
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
